PIHOLE_INTERFACE=eth0
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
CACHE_SIZE=10000
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSMASQ_LISTENING=local
# HOSTRECORD="piholebrad,192.168.2.91" feature deprecated
# WEBPASSWORD=3f4fa74468f336df5c4cf1d343d160f8948375732f82ea1a057138ae7d35055c
WEBPASSWORD=
BLOCKING_ENABLED=true
WEBUIBOXEDLAYOUT=boxed
WEBTHEME=default-auto
PIHOLE_DNS_1=208.67.222.222
PIHOLE_DNS_2=208.67.220.220
DNSSEC=false
REV_SERVER=false
PORT="8080o,443os,[::]:8080o,[::]:443os"
WEBPORT="7777o,443os,[::]:8080o,[::]:443os"
WEBSERVER.PORT="6666o,443os,[::]:8080o,[::]:443os"


    # setupVars.conf:WEBPASSWORD -> Setting webserver.api.pwhash to 
    # setupVars.conf:BLOCKING_ENABLED -> Setting dns.blocking.active to true
    # setupVars.conf:TEMPERATURE_LIMIT -> Not set
    # setupVars.conf:TEMPERATURE_UNIT -> Not set
    # setupVars.conf:WEBUIBOXEDLAYOUT -> Setting webserver.interface.boxed to true
    # setupVars.conf:WEBTHEME -> Setting webserver.interface.theme to lcars
    # setupVars.conf:PIHOLE_DNS_1 -> Setting dns.upstreams[1] = 208.67.222.222
    # setupVars.conf:PIHOLE_DNS_2 -> Setting dns.upstreams[2] = 208.67.220.220
    # setupVars.conf:PIHOLE_DOMAIN -> Not set
    # setupVars.conf:DNS_FQDN_REQUIRED -> Setting dns.domainNeeded to true
    # setupVars.conf:DNS_FQDN_REQUIRED -> Setting dns.expandHosts to true
    # setupVars.conf:DNS_BOGUS_PRIV -> Setting dns.bogusPriv to true
    # setupVars.conf:DNSSEC -> Setting dns.dnssec to false
    # setupVars.conf:PIHOLE_INTERFACE -> Setting dns.interface to eth0
    # setupVars.conf:HOSTRECORD -> Not set
    # setupVars.conf:DNSMASQ_LISTENING -> Setting dns.listeningMode to LOCAL
    # setupVars.conf:REV_SERVER_CIDR -> Not set
    # setupVars.conf:REV_SERVER_TARGET -> Not set
    # setupVars.conf:REV_SERVER_DOMAIN -> Not set
    # setupVars.conf:REV_SERVER_* -> Not set (found invalid/incomplete parameters)
    # setupVars.conf:DHCP_ACTIVE -> Not set
    # setupVars.conf:DHCP_START -> Not set
    # setupVars.conf:DHCP_END -> Not set
    # setupVars.conf:DHCP_ROUTER -> Not set
    # setupVars.conf:DHCP_LEASETIME -> Not set
    # setupVars.conf:DHCP_IPv6 -> Not set
    # setupVars.conf:DHCP_RAPID_COMMIT -> Not set
    # setupVars.conf:QUERY_LOGGING -> Setting dns.queryLogging to true
    # setupVars.conf:GRAVITY_TMPDIR -> Not set
    # setupVars.conf:WEB_PORTS -> Not set